### ISSUE TITLE
List inbox and send mail return `Exception: Content type text/html does not have a factory registered to be parsed`

### ISSUE THREAD

**Issue by eeintech** [microsoftgraph/msgraph-training-python#128]
**Where did you get the code?**
- [x] Downloaded from GitHub
- [ ] Downloaded from the [Microsoft Graph quick start tool](https://developer.microsoft.com/graph/quick-start)
- [ ] Followed the tutorial from [Microsoft Graph tutorials](https://learn.microsoft.com/graph/tutorials)

**Describe the bug**
Listing or sending email using the `user-auth\graphtutorial` code from this repo returns the following error (full traceback below):
``` shell
Exception: Content type text/html does not have a factory registered to be parsed
```

**To Reproduce**
1. Follow the tutorial, register an application, etc.
2. In `user-auth\graphtutorial`, run `python main.py` (Python 3.11)

``` shell
$ python main.py
Python Graph Tutorial

To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code ABCD1234 to authenticate.
Hello, Francois XXX
Email: francois.xxx@francoisxxxoutlook.onmicrosoft.com
```

4. Choose option 1

``` shell
Please choose one of the following options:
0. Exit
1. Display access token
2. List my inbox
3. Send mail
5. Make a Graph call
1
User token: eyJ0eXAiOiJKV1QiLCJub25jZSI6IlJYeG55U2NVeXByNHlTS0RxS01fU3ZVMF9HMnBvdzdycjFTNGpXcXNIRmciLCJhbGciOiJSUzI1NiIsIng1dCI6IlhSdmtvOFA3QTNVYVdTblU3Yk05blQwTWpoQSIsImtpZCI6IlhSdmtvOFA3QTNVYVdTblU3Yk05blQwTWpoQSJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC82MzFkYzhlMi03YmUyLTRkNGEtOGY1ZS1iZWI2NDhiNzU0ZWIvIiwiaWF0IjoxNzA5ODIwNDA3LCJuYmYiOjE3MDk4MjA0MDcsImV4cCI6MTcwOTgyNTEwMiwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkFZUUFlLzhXQUFBQW5la2VBcnVqaEdQbDkwL3dSdDBGb3JNL29kcDYyd08vdUxPV2hCdG1zVWIrMVZtVktEdnY5UXdha3JYdjdOSy80WlZIV3FEeHlmSDVtcXlUNko3UzlnYW9JWGhsY3crMXFST2szcldIVlhrcnVsaEJtaTdwKzFFYVYwdzFWZ3I2amFGcWtUN2NkREdMUzFoV0FXSUpTUVRLU3BTVHpxOXBxcTBobHIvY3kvRT0iLCJhbHRzZWNpZCI6IjE6bGl2ZS5jb206MDAwNjQwMDA5NkZDQkYwNiIsImFtciI6WyJwd2QiLCJtZmEiXSwiYXBwX2Rpc3BsYXluYW1lIjoiVGVzdCBBcHAiLCJhcHBpZCI6IjUyYzU0NTFkLWI1MzItNGE0NC1hNWI0LTJiNmI5NmE0MDVkZCIsImFwcGlkYWNyIjoiMCIsImVtYWlsIjoiZnJhbmNvaXMuZGVsYXJvY2hlQG91dGxvb2suY29tIiwiZmFtaWx5X25hbWUiOiJEZSBMYSBSb2NoZSIsImdpdmVuX25hbWUiOiJGcmFuY29pcyIsImlkcCI6ImxpdmUuY29tIiwiaWR0eXAiOiJ1c2VyIiwiaXBhZGRyIjoiMjA5LjEwNC4xMjMuMjEwIiwibmFtZSI6IkZyYW5jb2lzIERlIExhIFJvY2hlIiwib2lkIjoiYzMwY2JjOTktMTY0Yi00YzU4LWFjZWQtZmY4ZGNiMTA1ZmIyIiwicGxhdGYiOiIzIiwicHVpZCI6IjEwMDMyMDAzNUU2NjhDQTciLCJyaCI6IjAuQWFnQTRzZ2RZLUo3U2syUFhyNjJTTGRVNndNQUFBQUFBQUFBd0FBQUFBQUFBQUR6QVBNLiIsInNjcCI6Ik1haWwuUmVhZCBNYWlsLlNlbmQgb3BlbmlkIHByb2ZpbGUgVXNlci5SZWFkIGVtYWlsIiwic2lnbmluX3N0YXRlIjpbImttc2kiXSwic3ViIjoiVDEteXhtSzBKUzZCTUpYaktLSmNEZjFReVFkY253QlZJZ0NWN2IyZ1ZRdyIsInRlbmFudF9yZWdpb25fc2NvcGUiOiJOQSIsInRpZCI6IjYzMWRjOGUyLTdiZTItNGQ0YS04ZjVlLWJlYjY0OGI3NTRlYiIsInVuaXF1ZV9uYW1lIjoibGl2ZS5jb20jZnJhbmNvaXMuZGVsYXJvY2hlQG91dGxvb2suY29tIiwidXRpIjoiZ19fVHZMNGFsMEN6OWlweHdWMWZBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiNjJlOTAzOTQtNjlmNS00MjM3LTkxOTAtMDEyMTc3MTQ1ZTEwIiwiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19zdCI6eyJzdWIiOiJNa0p2aFpEWE5xYmJmRTBWV3l6cUZkLUN2QTRucTdwWUZfSVZjM0d3cWZJIn0sInhtc190Y2R0IjoxNzA5NzU5NzcyfQ.bhj-vu0XnxMsUWywmnvbzIgcqnOZs8mH3XZhE_1SVRVUXf1_YAoX_IN5AwbdWBCi9rb_b4IPOGueRujKy2_7XHkcxsY9sauR-EUubher9pKOy7tRSnQuikqEx26LYlqa7h9mn0d6gPAyAEzUqHxbTzgBShTJ7PKM74MIxD7o2wOLCsQU0_G17IrodAhVyZgpHJfSjaTwRB2Obaq3Fxq5dD_gwVfdlAP9d07xD1_Guk8MoK2wUyMD2F2muMh0-6kincUJcwYJJxx3gjWHxsN7OQGxTJMGv01MPuGI6d4nBmExxQph1bGLYHsjLP0k7odJLAeVvmNCLAe75Dnf9JaHKQ
```

6. Choose option 3 (send email)

``` shell
Please choose one of the following options:
0. Exit
1. Display access token
2. List my inbox
3. Send mail
4. Make a Graph call
3
Traceback (most recent call last):
  File "C:\development\tests\msgraph-training-python\user-auth\graphtutorial\main.py", line 112, in <module>
    asyncio.run(main())
  File "C:\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\development\tests\msgraph-training-python\user-auth\graphtutorial\main.py", line 45, in main
    await send_mail(graph)
  File "C:\development\tests\msgraph-training-python\user-auth\graphtutorial\main.py", line 102, in send_mail
    await graph.send_mail('Testing Microsoft Graph', 'Hello world!', user_email or '')
  File "C:\development\tests\msgraph-training-python\user-auth\graphtutorial\graph.py", line 93, in send_mail
    await self.user_client.me.send_mail.post(body=request_body)
  File "C:\development\tests\msgraph-training-python\user-auth\graphtutorial\.env\Lib\site-packages\msgraph\generated\users\item\send_mail\send_mail_request_builder.py", line 50, in post
    return await self.request_adapter.send_no_response_content_async(request_info, error_mapping)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\development\tests\msgraph-training-python\user-auth\graphtutorial\.env\Lib\site-packages\kiota_http\httpx_request_adapter.py", line 365, in send_no_response_content_async
    await self.throw_failed_responses(response, error_map, parent_span, parent_span)
  File "C:\development\tests\msgraph-training-python\user-auth\graphtutorial\.env\Lib\site-packages\kiota_http\httpx_request_adapter.py", line 464, in throw_failed_responses
    root_node = await self.get_root_parse_node(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\development\tests\msgraph-training-python\user-auth\graphtutorial\.env\Lib\site-packages\kiota_http\httpx_request_adapter.py", line 400, in get_root_parse_node
    return self._parse_node_factory.get_root_parse_node(response_content_type, payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\development\tests\msgraph-training-python\user-auth\graphtutorial\.env\Lib\site-packages\kiota_abstractions\serialization\parse_node_factory_registry.py", line 50, in get_root_parse_node
    raise Exception(
Exception: Content type text/html does not have a factory registered to be parsed
```

**Expected behavior**
It should send the email with no error.

**Screenshots**
Checking the token claims on jwt.ms, I can see the scopes for the application are correct:
![image](https://github.com/microsoftgraph/msgraph-training-python/assets/4020546/00056f5b-3bd8-48bf-93fc-a6b8003a8a15)

I'm using a free Azure account, here's screenshot of the app overview:
![image](https://github.com/microsoftgraph/msgraph-training-python/assets/4020546/9824eb05-2c29-4754-8c74-81953d580809)

Here are the permissions:
![image](https://github.com/microsoftgraph/msgraph-training-python/assets/4020546/7f7d60c2-3a7e-4195-af1a-934770fb140e)

**Desktop (please complete the following information):**
 - OS: Windows 11 Enterprise Version 10.0.22631 Build 22631
 - Browser: Chrome 122.0.6261.96

**Dependency versions**
``` shell
$ pip freeze
aiohttp==3.9.2
aiosignal==1.3.1
anyio==4.0.0
async-timeout==4.0.3
attrs==23.1.0
azure-core==1.29.5
azure-identity==1.15.0
certifi==2023.7.22
cffi==1.16.0
charset-normalizer==3.3.2
cryptography==41.0.6
Deprecated==1.2.14
exceptiongroup==1.1.3
frozenlist==1.4.0
h11==0.14.0
h2==4.1.0
hpack==4.0.0
httpcore==0.18.0
httpx==0.25.0
hyperframe==6.0.1
idna==3.4
importlib-metadata==6.8.0
microsoft-kiota-abstractions==1.0.0
microsoft-kiota-authentication-azure==1.0.0
microsoft-kiota-http==1.0.0
microsoft-kiota-serialization-json==1.0.0
microsoft-kiota-serialization-text==1.0.0
msal==1.24.1
msal-extensions==1.0.0
msgraph-core==1.0.0
msgraph-sdk==1.1.0
multidict==6.0.4
opentelemetry-api==1.20.0
opentelemetry-sdk==1.20.0
opentelemetry-semantic-conventions==0.41b0
pendulum==2.1.2
portalocker==2.8.2
pycparser==2.21
PyJWT==2.8.0
python-dateutil==2.8.2
pytzdata==2020.1
pywin32==306
requests==2.31.0
six==1.16.0
sniffio==1.3.0
std-uritemplate==0.0.46
typing_extensions==4.8.0
urllib3==2.0.7
wrapt==1.15.0
yarl==1.9.2
zipp==3.17.0
```

**Additional context**
Using Git Bash.

Out of curiosity, why do I need an application for user authentication?

**Comment by jasonjoh** [comment]
@eeintech The error seems to indicate that the API is sending back HTML in the response, rather than the expected JSON. This would be some unexpected error from the Microsoft Graph service. Could you try making a similar request using [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) with the same user account? The equivalent list mailbox query would be:

```
GET https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messages?$select=from,isRead,receivedDateTime,subject&$top=25&$orderby=receivedDateTime%20DESC
```

> Out of curiosity, why do I need an application for user authentication?

I assume you're referring to the app registration? That's a requirement of [Microsoft Entra ID's OAuth 2.0 implementation](https://learn.microsoft.com/en-us/entra/architecture/auth-oauth2). I believe all OAuth implemenations require it in some form (to get a client ID). See https://www.oauth.com/oauth2-servers/client-registration/client-id-secret/.

**Comment by eeintech** [comment]
> @eeintech The error seems to indicate that the API is sending back HTML in the response, rather than the expected JSON. This would be some unexpected error from the Microsoft Graph service. Could you try making a similar request using [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) with the same user account? The equivalent list mailbox query would be:

Using GraphExplorer, at first it fails with this error:
``` json
{
    "error": {
        "code": "ErrorAccessDenied",
        "message": "Access is denied. Check credentials and try again."
    }
}
```

And it is explicitly telling me how to fix it: ` Either the signed-in user does not have sufficient privileges, or you need to consent to one of the permissions on the Modify permissions tab`
After a consent to `Mail.Read` it works fine. Same process if I want to send an email.

And then if I go back to my Test App, still the same error...

My main problem is that I believe Graph Explorer and this tutorial are two quite different setups, I never have to register an application, specify tenant and client ID, etc. in Graph Explorer, so it is neat for so some quick testing but does not explain the discrepancy. It feels like something missing in the tutorial to tell you how to get the same point...

**Comment by jasonjoh** [comment]
> My main problem is that I believe Graph Explorer and this tutorial/sample app are two quite different setups, I never have to register an application, specify tenant and client ID, etc. in Graph Explorer, so it is neat for so some quick testing but does not explain the discrepancy. It feels like something missing in the tutorial to tell you how to get the same point...

Yes, that's right. I just wanted to test if there was an API/service problem unrelated to the code. For the API to return HTML, something unexpected is happening. Are you behind a proxy perhaps?

I also noticed that some of your dependencies are older versions. Try this command to update:

```bash
pip install -r requirements.in --upgrade --upgrade-strategy eager
```

**Comment by eeintech** [comment]
@jasonjoh I have tried updating the dependencies (you were right they were older) but I'm not getting this error:

``` shell
Error:
MailboxNotEnabledForRESTAPI The mailbox is either inactive, soft-deleted, or is hosted on-premise.
```

I am not sure about the proxy, could this error be because of it?

**Comment by jasonjoh** [comment]
That error indicates there is an issue with the authenticated user's mailbox that makes Graph unable to access it. In order to access the mailbox, it must be an Exchange Online or Outlook.com mailbox. If this is your work email, you may need to check with your IT admins to verify what type of mailbox you have. 

However you said it worked for you in Graph Explorer - are you authenticating as the same user?

**Comment by eeintech** [comment]
When I run `python main.py` I get this:

``` shell
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code ABCD12345 to authenticate.
Hello, Francois XXX
Email: francois.xxx@francoisxxxoutlook.onmicrosoft.com
```

but my actual email address is `francois.xxx@outlook.com`

Not sure why the email shown in the intro message does not match with my actual email address? 🤔

**Comment by jasonjoh** [comment]
That looks similar to what I've seen with a guest account in a Microsoft 365 tenant. If you're authenticating as a guest, you won't be able to access your mailbox.

When you registered your application, did you choose the option for "Supported account types" that includes personal Microsoft accounts?

**Comment by jasonjoh** [comment]
Ok. Let's try this. If you can register an app and choose "Personal Microsoft accounts only":

![image](https://github.com/microsoftgraph/msgraph-training-python/assets/8966342/3771b95d-8cd6-471f-baba-40f98b878270)

Then on the **Authentication** tab, make sure to turn on **Allow public client flows** (be sure to **Save** after toggling the setting):

![image](https://github.com/microsoftgraph/msgraph-training-python/assets/8966342/09b0d084-0320-4a37-9801-04fa9e86c36f)

Then update the `clientId` and `tenantId` in config.cfg. Set `clientId` to the new client ID from this app registration, and set `tenantId` to `consumers`.

The end result should be that the prompt is slightly different:

```bash
Python Graph Tutorial

To sign in, use a web browser to open the page https://www.microsoft.com/link and enter the code EQ9N4HVL to authenticate.
```

**Comment by eeintech** [comment]
@jasonjoh Ha yes I had forgot about allowing the public client flow. And I did not know about setting the `tenantId = consumers`! In the tutorial, it tells to use the tenant ID of the application:

**Comment by eeintech** [comment]
@jasonjoh Ha yes I had forgot about allowing the public client flow, thank you for the reminder. And I did not know about setting the `tenantId = consumers`! In the tutorial, it tells to use the tenant ID of the application:
![image](https://github.com/microsoftgraph/msgraph-training-python/assets/4020546/5b0b6acf-c2cd-4c47-895d-bb98d1555831)

![image](https://github.com/microsoftgraph/msgraph-training-python/assets/4020546/2f38a1d8-9a4e-49b8-a43c-a37d6e3d1458)

Maybe it should be added to the documentation?

Now it works fine for the "Personal Microsoft accounts only" app, not sure why the other type of apps don't work with the tutorial...

**Comment by jasonjoh** [comment]
Yes - you should set `tenantId` to your actual tenant ID only if you chose the "Accounts in this organizational directory only" option. Since you're using a personal account, this option would not be valid for you - personal accounts are not part of any organizational directory.

I'm glad that got you unblocked!

**Comment by eeintech** [comment]
Understood, thanks a lot for the help @jasonjoh !
